export const DEFAULT_REGIONS = [
  { slug: 'africa', name: 'Africa' },
  { slug: 'antarctica', name: 'Antarctica' },
  { slug: 'asia', name: 'Asia' },
  { slug: 'europe', name: 'Europe' },
  { slug: 'north-america', name: 'North America' },
  { slug: 'south-america', name: 'South America' },
  { slug: 'oceania', name: 'Oceania' },
  { slug: 'middle-east', name: 'Middle East' },
  { slug: 'caribbean', name: 'Caribbean' },
  { slug: 'central-america', name: 'Central America' },
  { slug: 'central-asia', name: 'Central Asia' },
  { slug: 'east-asia', name: 'East Asia' },
  { slug: 'south-asia', name: 'South Asia' },
  { slug: 'southeast-asia', name: 'Southeast Asia' },
  { slug: 'western-europe', name: 'Western Europe' },
  { slug: 'eastern-europe', name: 'Eastern Europe' },
  { slug: 'northern-europe', name: 'Northern Europe' },
  { slug: 'southern-europe', name: 'Southern Europe' },
  { slug: 'australasia', name: 'Australasia' },
];
